INDIAN_LANGUAGES = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'bn': 'বাংলা (Bengali)',
    'te': 'తెలుగు (Telugu)',
    'mr': 'मराठी (Marathi)',
    'ta': 'தமிழ் (Tamil)',
    'gu': 'ગુજરાતી (Gujarati)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'ml': 'മലയാളം (Malayalam)',
    'pa': 'ਪੰਜਾਬੀ (Punjabi)',
    'or': 'ଓଡ଼ିଆ (Odia)',
    'as': 'অসমীয়া (Assamese)',
    'ur': 'اردو (Urdu)',
    'sa': 'संस्कृत (Sanskrit)',
    'ks': 'कॉशुर (Kashmiri)',
    'sd': 'سنڌي (Sindhi)',
    'ne': 'नेपाली (Nepali)',
    'si': 'සිංහල (Sinhala)',
    'my': 'မြန်မာ (Myanmar)',
    'dz': 'རྫོང་ཁ (Dzongkha)',
    'bh': 'भोजपुरी (Bhojpuri)',
    'mai': 'मैथिली (Maithili)',
    'sat': 'ᱥᱟᱱᱛᱟᱲᱤ (Santali)',
    'kok': 'कोंकणी (Konkani)',
    'mni': 'মৈতৈলোন্ (Manipuri)',
    'doi': 'डोगरी (Dogri)'
}

TRANSLATIONS = {
    'en': {
        'welcome': 'Welcome to AgriSmart AI',
        'login': 'Login',
        'register': 'Register',
        'username': 'Username',
        'password': 'Password',
        'email': 'Email',
        'language': 'Language',
        'crop_recommendation': 'Crop Recommendation',
        'fertilizer_recommendation': 'Fertilizer Recommendation',
        'disease_detection': 'Disease Detection',
        'logout': 'Logout',
        'nitrogen': 'Nitrogen (N)',
        'phosphorus': 'Phosphorus (P)',
        'potassium': 'Potassium (K)',
        'temperature': 'Temperature (°C)',
        'humidity': 'Humidity (%)',
        'ph_level': 'pH Level',
        'rainfall': 'Rainfall (mm)',
        'get_recommendation': 'Get Recommendation',
        'analyzing': 'Analyzing...',
        'crop_desc': 'Find the best crop for your soil conditions',
        'description': 'Get personalized crop recommendations, fertilizer guidance, and disease detection using advanced machine learning algorithms trained on agricultural data.',
        'welcome_user': 'Welcome',
        'results': 'Results & Insights',
        'submit_data': 'Submit your data to get AI-powered recommendations'
    },
    'hi': {
        'welcome': 'एग्रीस्मार्ट एआई में आपका स्वागत है',
        'login': 'लॉगिन',
        'register': 'पंजीकरण',
        'username': 'उपयोगकर्ता नाम',
        'password': 'पासवर्ड',
        'email': 'ईमेल',
        'language': 'भाषा',
        'crop_recommendation': 'फसल सिफारिश',
        'fertilizer_recommendation': 'उर्वरक सिफारिश',
        'disease_detection': 'रोग का पता लगाना',
        'logout': 'लॉगआउट',
        'nitrogen': 'नाइट्रोजन (N)',
        'phosphorus': 'फास्फोरस (P)',
        'potassium': 'पोटेशियम (K)',
        'temperature': 'तापमान (°C)',
        'humidity': 'आर्द्रता (%)',
        'ph_level': 'पीएच स्तर',
        'rainfall': 'वर्षा (मिमी)',
        'get_recommendation': 'सिफारिश प्राप्त करें',
        'analyzing': 'विश्लेषण कर रहे हैं...',
        'crop_desc': 'अपनी मिट्टी की स्थिति के लिए सबसे अच्छी फसल खोजें',
        'description': 'उन्नत मशीन लर्निंग अल्गोरिदम का उपयोग करके व्यक्तिगत फसल सिफारिश, उर्वरक मार्गदर्शन और रोग का पता लगाएं',
        'welcome_user': 'आपका स्वागत है',
        'results': 'परिणाम और अंतर्दृष्टि',
        'submit_data': 'एआई-संचालित सिफारिशें प्राप्त करने के लिए अपना डेटा जमा करें'
    },
    'bn': {
        'welcome': 'এগ্রিস্মার্ট এআই-তে স্বাগতম',
        'login': 'লগইন',
        'register': 'নিবন্ধন',
        'username': 'ব্যবহারকারীর নাম',
        'password': 'পাসওয়ার্ড',
        'email': 'ইমেইল',
        'language': 'ভাষা',
        'crop_recommendation': 'ফসলের সুপারিশ',
        'fertilizer_recommendation': 'সারের সুপারিশ',
        'disease_detection': 'রোগ সনাক্তকরণ',
        'logout': 'লগআউট',
        'nitrogen': 'নাইট্রোজেন (N)',
        'phosphorus': 'ফসফরাস (P)',
        'potassium': 'পটাসিয়াম (K)',
        'temperature': 'তাপমাত্রা (°C)',
        'humidity': 'আর্দ্রতা (%)',
        'ph_level': 'পিএইচ স্তর',
        'rainfall': 'বৃষ্টিপাত (মিমি)',
        'get_recommendation': 'সুপারিশ পান',
        'analyzing': 'বিশ্লেষণ করা হচ্ছে...',
        'crop_desc': 'আপনার মাটির অবস্থার জন্য সেরা ফসল খুঁজুন',
        'description': 'উন্নত মেশিন লার্নিং অ্যালগোরিদম ব্যবহার করে ব্যক্তিগত ফসলের সুপারিশ, সারের নির্দেশনা এবং রোগ সনাক্তকরণ পান',
        'welcome_user': 'আপনাকে স্বাগতম',
        'results': 'ফলাফল এবং অন্তর্দৃষ্টি',
        'submit_data': 'এআই-চালিত সুপারিশ পেতে আপনার ডেটা জমা দিন'
    },
    'ta': {
        'welcome': 'அக்ரிஸ்மார்ட் AI க்கு வரவேற்கிறோம்',
        'login': 'உள்நுழைய',
        'register': 'பதிவு செய்ய',
        'username': 'பயனர் பெயர்',
        'password': 'கடவுச்சொல்',
        'email': 'மின்னஞ்சல்',
        'language': 'மொழி',
        'crop_recommendation': 'பயிர் பரிந்துரை',
        'fertilizer_recommendation': 'உர பரிந்துரை',
        'disease_detection': 'நோய் கண்டறிதல்',
        'logout': 'வெளியேறு',
        'nitrogen': 'நைட்ரஜன் (N)',
        'phosphorus': 'பாஸ்பரஸ் (P)',
        'potassium': 'பொட்டாசியம் (K)',
        'temperature': 'வெப்பநிலை (°C)',
        'humidity': 'ஈரப்பதம் (%)',
        'ph_level': 'பிஎச் அளவு',
        'rainfall': 'மழைப்பொழிவு (மிமீ)',
        'get_recommendation': 'பரிந்துரை பெறுங்கள்',
        'analyzing': 'பகுப்பாய்வு செய்கிறது...',
        'crop_desc': 'உங்கள் மண் நிலைமைக்கு சிறந்த பயிரைக் கண்டறியுங்கள்',
        'description': 'மேம்பட்ட மெஷீன் லர்னிங் அல்காரிதம்களைப் பயன்படுத்தி தனிப்பட்ட பயிர் பரிந்துரைகள், உர வழிகாட்டல் மற்றும் நோய் கண்டறிதல் பெறுங்கள்',
        'welcome_user': 'வணக்கம்',
        'results': 'முடிவுகள் மற்றும் அறிவுறுத்தல்கள்',
        'submit_data': 'எஆஇ-சக்தி பெற்ற பரிந்துரைகளைப் பெற உங்கள் தகவலை சமர்ப்பிக்கவும்'
    }
}